export const ADD_ALL_COIN_IDS = "ADD_ALL_COIN_IDS";
export const ADD_COIN_TO_WATCHLIST = "ADD_COIN_TO_WATCHLIST";
export const REMOVE_COIN_FROM_WATCHLIST = "REMOVE_COIN_FROM_WATCHLIST";
export const ADD_COIN_TO_PORTFOLIO = "ADD_COIN_TO_PORTFOLIO";
export const REMOVE_COIN_FROM_PORTFOLIO = "REMOVE_COIN_FROM_PORTFOLIO";
export const CHANGE_PORTFOLIO_NAME = "CHANGE_PORTFOLIO_NAME";
export const REMOVE_PORTFOLIO = "REMOVE_PORTFOLIO";
