export const ADD_ALL_COIN_IDS = "ADD_ALL_COIN_IDS";
export const ADD_COIN_TO_LIST = "ADD_COIN_TO_LIST";
export const REMOVE_COIN_FROM_LIST = "REMOVE_COIN_FROM_LIST";
export const ADD_COIN_TO_WATCHLIST = "ADD_COIN_TO_WATCHLIST";
export const REMOVE_COIN_FROM_WATCHLIST = "REMOVE_COIN_FROM_WATCHLIST";
export const ADD_COIN_TO_PORTFOLIO = "ADD_COIN_TO_PORTFOLIO";
export const REMOVE_COIN_FROM_PORTFOLIO = "REMOVE_COIN_FROM_PORTFOLIO";
